package com.gamq.ambiente.dto.mapper;

import com.gamq.ambiente.dto.*;
import com.gamq.ambiente.model.Certificado;
import com.gamq.ambiente.model.Equipo;
import com.gamq.ambiente.model.Inspeccion;

public class CertificadoMapper {
    public static CertificadoDto toCertificadoDto(Certificado certificado){
        return new CertificadoDto()
                .setUuid(certificado.getUuid())
                .setCodigo(certificado.getCodigo())
                .setEsValido(certificado.isEsValido())
                .setFechaEmision(certificado.getFechaEmision())
                .setFechaVencimiento(certificado.getFechaVencimiento())
                .setQrContent(certificado.getQrContent())
                .setEstado(certificado.isEstado())
                .setInspeccionDto(certificado.getInspeccion() == null? null: new InspeccionDto()
                        .setUuid(certificado.getInspeccion().getUuid())
                        .setResultado(certificado.getInspeccion().isResultado())
                        .setObservacion(certificado.getInspeccion().getObservacion())
                        .setFechaInspeccion(certificado.getInspeccion().getFechaInspeccion())
                        .setLugarInspeccion(certificado.getInspeccion().getLugarInspeccion())
                        .setNombreInspector(certificado.getInspeccion().getNombreInspector())
                        .setUuidUsuario(certificado.getInspeccion().getUuidUsuario())
                        .setAltitud(certificado.getInspeccion().getAltitud())
                        //.setEquipo(certificado.getInspeccion().getEquipo())
                        .setExamenVisualConforme(certificado.getInspeccion().isExamenVisualConforme())
                        .setGasesEscapeConforme(certificado.getInspeccion().isGasesEscapeConforme())
                        .setFechaProximaInspeccion(certificado.getInspeccion().getFechaProximaInspeccion())
                        .setEstado(certificado.getInspeccion().isEstado())
                        .setEquipoDto(certificado.getInspeccion().getEquipo() == null? null: new EquipoDto()
                                .setUuid(certificado.getInspeccion().getEquipo().getUuid())
                                .setNombre(certificado.getInspeccion().getEquipo().getNombre())
                                .setVersion(certificado.getInspeccion().getEquipo().getVersion())
                                .setEstado(certificado.getInspeccion().getEquipo().isEstado())
                        )
                        .setActividadDto(certificado.getInspeccion().getActividad() == null? null: new ActividadDto()
                                .setUuid(certificado.getInspeccion().getActividad().getUuid())
                                .setActivo(certificado.getInspeccion().getActividad().isActivo())
                                .setTipoActividad(certificado.getInspeccion().getActividad().getTipoActividad())
                                .setFechaInicio(certificado.getInspeccion().getActividad().getFechaInicio())
                                .setFechaFin(certificado.getInspeccion().getActividad().getFechaFin())
                                .setEstado(certificado.getInspeccion().getActividad().isEstado())
                        )
                        .setVehiculoDto(certificado.getInspeccion().getVehiculo() == null? null: new VehiculoDto()
                                .setUuid(certificado.getInspeccion().getVehiculo().getUuid())
                                .setPlaca(certificado.getInspeccion().getVehiculo().getPlaca())
                                .setPoliza(certificado.getInspeccion().getVehiculo().getPoliza())
                                .setVinNumeroIdentificacion(certificado.getInspeccion().getVehiculo().getVinNumeroIdentificacion())
                                .setEsOficial(certificado.getInspeccion().getVehiculo().isEsOficial())
                                .setFechaRegistro(certificado.getInspeccion().getVehiculo().getFechaRegistro())
                                .setJurisdiccionOrigen(certificado.getInspeccion().getVehiculo().getJurisdiccionOrigen())
                                .setEsMovil(certificado.getInspeccion().getVehiculo().getEsMovil())
                                .setEsUnidadIndustrial(certificado.getInspeccion().getVehiculo().isEsUnidadIndustrial())
                                .setPinNumeroIdentificacion(certificado.getInspeccion().getVehiculo().getPinNumeroIdentificacion())
                                .setNroCopiasPlaca(certificado.getInspeccion().getVehiculo().getNroCopiasPlaca())
                                .setPlacaAnterior(certificado.getInspeccion().getVehiculo().getPlacaAnterior())
                                .setChasis(certificado.getInspeccion().getVehiculo().getChasis())
                                .setEstado(certificado.getInspeccion().getVehiculo().isEstado())
                                .setDatoTecnicoDto( certificado.getInspeccion().getVehiculo().getDatoTecnico() == null? null: new DatoTecnicoDto()
                                        .setUuid(certificado.getInspeccion().getVehiculo().getDatoTecnico().getUuid())
                                        .setTipoVehiculo(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTipoVehiculo())
                                        .setCapacidadCarga(certificado.getInspeccion().getVehiculo().getDatoTecnico().getCapacidadCarga())
                                        .setCilindrada(certificado.getInspeccion().getVehiculo().getDatoTecnico().getCilindrada())
                                        .setClase(certificado.getInspeccion().getVehiculo().getDatoTecnico().getClase())
                                        .setColor(certificado.getInspeccion().getVehiculo().getDatoTecnico().getColor())
                                        .setEmisionStandard(certificado.getInspeccion().getVehiculo().getDatoTecnico().getEmisionStandard())
                                        .setEstado(certificado.getInspeccion().getVehiculo().getDatoTecnico().isEstado())
                                        .setKilometraje(certificado.getInspeccion().getVehiculo().getDatoTecnico().getKilometraje())
                                        .setMarca(certificado.getInspeccion().getVehiculo().getDatoTecnico().getMarca())
                                        .setColor(certificado.getInspeccion().getVehiculo().getDatoTecnico().getColor())
                                        .setModelo(certificado.getInspeccion().getVehiculo().getDatoTecnico().getModelo())
                                        .setNumeroPuertas(certificado.getInspeccion().getVehiculo().getDatoTecnico().getNumeroPuertas())
                                        .setPais(certificado.getInspeccion().getVehiculo().getDatoTecnico().getPais())
                                        .setServicio(certificado.getInspeccion().getVehiculo().getDatoTecnico().getServicio())
                                        .setTamanoMotor(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTamanoMotor())
                                        .setTipoCarroceria(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTipoCarroceria())
                                        .setTipoCombustion(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTipoCombustion())
                                        .setTraccion(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTraccion())
                                        .setTipoMotor(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTipoMotor())
                                        .setYearFabricacion(certificado.getInspeccion().getVehiculo().getDatoTecnico().getYearFabricacion())
                                        .setClasificacion(certificado.getInspeccion().getVehiculo().getDatoTecnico().getClasificacion())
                                        .setNumeroAsientos(certificado.getInspeccion().getVehiculo().getDatoTecnico().getNumeroAsientos())
                                        .setTiempoMotor(certificado.getInspeccion().getVehiculo().getDatoTecnico().getTiempoMotor())
                                        .setCategoriaVehiculo(certificado.getInspeccion().getVehiculo().getDatoTecnico().getCategoriaVehiculo())
                                        .setEstado(certificado.getInspeccion().getVehiculo().getDatoTecnico().isEstado())
                                )
                        )
                        .setConductorDto( certificado.getInspeccion().getConductor() == null? null: new ConductorDto()
                        .setUuid(certificado.getInspeccion().getConductor().getUuid())
                        .setNombre(certificado.getInspeccion().getConductor().getNombre())
                        .setPrimerApellido(certificado.getInspeccion().getConductor().getPrimerApellido())
                        .setSegundoApellido(certificado.getInspeccion().getConductor().getSegundoApellido())
                        .setApellidoEsposo(certificado.getInspeccion().getConductor().getApellidoEsposo())
                        .setTipoDocumento(certificado.getInspeccion().getConductor().getTipoDocumento())
                        .setNumeroDocumento(certificado.getInspeccion().getConductor().getNumeroDocumento())
                        .setExpedido(certificado.getInspeccion().getConductor().getExpedido())
                        .setNroTelefono(certificado.getInspeccion().getConductor().getNroTelefono())
                        .setEmail(certificado.getInspeccion().getConductor().getEmail())
                        .setEstado(certificado.getInspeccion().getConductor().isEstado())
                        .setTipoContribuyenteDto(certificado.getInspeccion().getConductor().getTipoContribuyente()==null? null: new TipoContribuyenteDto()
                                .setUuid(certificado.getInspeccion().getConductor().getTipoContribuyente().getUuid())
                                .setDescripcion(certificado.getInspeccion().getConductor().getTipoContribuyente().getDescripcion())
                                .setEstado(certificado.getInspeccion().getConductor().getTipoContribuyente().isEstado())
                                .setCodigo(certificado.getInspeccion().getConductor().getTipoContribuyente().getCodigo())
                        )
                )
                );
    }
    public static Certificado toCertificado(CertificadoDto certificadoDto){
        return new Certificado()
                .setUuid(certificadoDto.getUuid())
                .setCodigo(certificadoDto.getCodigo())
                .setEsValido(certificadoDto.isEsValido())
                .setFechaEmision(certificadoDto.getFechaEmision())
                .setFechaVencimiento(certificadoDto.getFechaVencimiento())
                .setQrContent(certificadoDto.getQrContent())
                .setEstado(certificadoDto.isEstado())
                .setInspeccion(certificadoDto.getInspeccionDto() == null? null: new Inspeccion()
                        .setUuid(certificadoDto.getInspeccionDto().getUuid())
                        .setFechaInspeccion(certificadoDto.getInspeccionDto().getFechaInspeccion())
                        .setResultado(certificadoDto.getInspeccionDto().isResultado())
                        .setObservacion(certificadoDto.getInspeccionDto().getObservacion())
                        .setLugarInspeccion(certificadoDto.getInspeccionDto().getLugarInspeccion())
                        .setNombreInspector(certificadoDto.getInspeccionDto().getNombreInspector())
                        .setUuidUsuario(certificadoDto.getInspeccionDto().getUuidUsuario())
                        .setAltitud(certificadoDto.getInspeccionDto().getAltitud())
                       // .setEquipo(certificadoDto.getInspeccionDto().getEquipo())
                        .setEstado(certificadoDto.getInspeccionDto().isEstado())
                        .setEquipo(certificadoDto.getInspeccionDto().getEquipoDto() == null? null: new Equipo()
                                .setUuid(certificadoDto.getInspeccionDto().getEquipoDto().getUuid())
                                .setNombre(certificadoDto.getInspeccionDto().getEquipoDto().getNombre())
                                .setVersion(certificadoDto.getInspeccionDto().getEquipoDto().getVersion())
                                .setEstado(certificadoDto.getInspeccionDto().getEquipoDto().isEstado())
                        )
                );
    }
}
