package com.gamq.ambiente.dto.mapper;

import com.gamq.ambiente.dto.*;
import com.gamq.ambiente.model.Actividad;
import com.gamq.ambiente.model.Inspeccion;
import com.gamq.ambiente.model.Propietario;
import com.gamq.ambiente.model.Vehiculo;

import java.util.stream.Collectors;

public class InspeccionMapper {
    public static InspeccionDto toInspeccionDto(Inspeccion inspeccion){
        return new InspeccionDto()
                .setUuid(inspeccion.getUuid())
                .setResultado(inspeccion.isResultado())
                .setObservacion(inspeccion.getObservacion())
                .setFechaInspeccion(inspeccion.getFechaInspeccion())
                .setLugarInspeccion(inspeccion.getLugarInspeccion())
                .setNombreInspector(inspeccion.getNombreInspector())
                .setUuidUsuario(inspeccion.getUuidUsuario())
                .setAltitud(inspeccion.getAltitud())
                .setEquipo(inspeccion.getEquipo())
                .setExamenVisualConforme(inspeccion.isExamenVisualConforme())
                .setGasesEscapeConforme(inspeccion.isGasesEscapeConforme())
                .setFechaProximaInspeccion(inspeccion.getFechaProximaInspeccion())
                .setEstado(inspeccion.isEstado())
                .setActividadDto(inspeccion.getActividad() == null? null: new ActividadDto()
                        .setUuid(inspeccion.getActividad().getUuid())
                        .setActivo(inspeccion.getActividad().isActivo())
                        .setTipoActividad(inspeccion.getActividad().getTipoActividad())
                        .setFechaInicio(inspeccion.getActividad().getFechaInicio())
                        .setFechaFin(inspeccion.getActividad().getFechaFin())
                        .setEstado(inspeccion.getActividad().isEstado())
                )
                .setVehiculoDto(inspeccion.getVehiculo() == null? null: new VehiculoDto()
                        .setUuid(inspeccion.getVehiculo().getUuid())
                        .setPlaca(inspeccion.getVehiculo().getPlaca())
                        .setPoliza(inspeccion.getVehiculo().getPoliza())
                        .setVinNumeroIdentificacion(inspeccion.getVehiculo().getVinNumeroIdentificacion())
                        .setEsOficial(inspeccion.getVehiculo().isEsOficial())
                        .setFechaRegistro(inspeccion.getVehiculo().getFechaRegistro())
                        .setJurisdiccionOrigen(inspeccion.getVehiculo().getJurisdiccionOrigen())
                        .setEsMovil(inspeccion.getVehiculo().getEsMovil())
                        .setEsUnidadIndustrial(inspeccion.getVehiculo().isEsUnidadIndustrial())
                        .setPinNumeroIdentificacion(inspeccion.getVehiculo().getPinNumeroIdentificacion())
                        .setNroCopiasPlaca(inspeccion.getVehiculo().getNroCopiasPlaca())
                        .setPlacaAnterior(inspeccion.getVehiculo().getPlacaAnterior())
                        .setChasis(inspeccion.getVehiculo().getChasis())
                        .setEstado(inspeccion.getVehiculo().isEstado())
                        .setDatoTecnicoDto( inspeccion.getVehiculo().getDatoTecnico() == null? null: new DatoTecnicoDto()
                                .setUuid(inspeccion.getVehiculo().getDatoTecnico().getUuid())
                                .setTipoVehiculo(inspeccion.getVehiculo().getDatoTecnico().getTipoVehiculo())
                                .setCapacidadCarga(inspeccion.getVehiculo().getDatoTecnico().getCapacidadCarga())
                                .setCilindrada(inspeccion.getVehiculo().getDatoTecnico().getCilindrada())
                                .setClase(inspeccion.getVehiculo().getDatoTecnico().getClase())
                                .setColor(inspeccion.getVehiculo().getDatoTecnico().getColor())
                                .setEmisionStandard(inspeccion.getVehiculo().getDatoTecnico().getEmisionStandard())
                                .setEstado(inspeccion.getVehiculo().getDatoTecnico().isEstado())
                                .setKilometraje(inspeccion.getVehiculo().getDatoTecnico().getKilometraje())
                                .setMarca(inspeccion.getVehiculo().getDatoTecnico().getMarca())
                                .setColor(inspeccion.getVehiculo().getDatoTecnico().getColor())
                                .setModelo(inspeccion.getVehiculo().getDatoTecnico().getModelo())
                                .setNumeroPuertas(inspeccion.getVehiculo().getDatoTecnico().getNumeroPuertas())
                                .setPais(inspeccion.getVehiculo().getDatoTecnico().getPais())
                                .setServicio(inspeccion.getVehiculo().getDatoTecnico().getServicio())
                                .setTamanoMotor(inspeccion.getVehiculo().getDatoTecnico().getTamanoMotor())
                                .setTipoCarroceria(inspeccion.getVehiculo().getDatoTecnico().getTipoCarroceria())
                                .setTipoCombustion(inspeccion.getVehiculo().getDatoTecnico().getTipoCombustion())
                                .setTraccion(inspeccion.getVehiculo().getDatoTecnico().getTraccion())
                                .setTipoMotor(inspeccion.getVehiculo().getDatoTecnico().getTipoMotor())
                                .setYearFabricacion(inspeccion.getVehiculo().getDatoTecnico().getYearFabricacion())
                                .setClasificacion(inspeccion.getVehiculo().getDatoTecnico().getClasificacion())
                                .setNumeroAsientos(inspeccion.getVehiculo().getDatoTecnico().getNumeroAsientos())
                                .setTiempoMotor(inspeccion.getVehiculo().getDatoTecnico().getTiempoMotor())
                                .setCategoriaVehiculo(inspeccion.getVehiculo().getDatoTecnico().getCategoriaVehiculo())
                                .setEstado(inspeccion.getVehiculo().getDatoTecnico().isEstado())
                        )

                        .setPropietarioDto(inspeccion.getVehiculo().getPropietario()== null? null: new PropietarioDto()
                                .setUuid(inspeccion.getVehiculo().getPropietario().getUuid())
                                .setNombre(inspeccion.getVehiculo().getPropietario().getNombre())
                                .setPrimerApellido(inspeccion.getVehiculo().getPropietario().getPrimerApellido())
                                .setSegundoApellido(inspeccion.getVehiculo().getPropietario().getSegundoApellido())
                                .setApellidoEsposo(inspeccion.getVehiculo().getPropietario().getApellidoEsposo())
                                .setEstadoCivil(inspeccion.getVehiculo().getPropietario().getEstadoCivil())
                                .setGenero(inspeccion.getVehiculo().getPropietario().getGenero())
                                .setFechaNacimiento(inspeccion.getVehiculo().getPropietario().getFechaNacimiento())
                                .setNumeroDocumento(inspeccion.getVehiculo().getPropietario().getNumeroDocumento())
                                .setTipoDocumento(inspeccion.getVehiculo().getPropietario().getTipoDocumento())
                                .setExpedido(inspeccion.getVehiculo().getPropietario().getExpedido())
                                .setEmail(inspeccion.getVehiculo().getPropietario().getEmail())
                                .setNroTelefono(inspeccion.getVehiculo().getPropietario().getNroTelefono())
                                .setEstado(inspeccion.getVehiculo().getPropietario().isEstado())
                                .setTipoContribuyenteDto(inspeccion.getVehiculo().getPropietario().getTipoContribuyente()== null? null: new TipoContribuyenteDto()
                                        .setUuid(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getUuid())
                                        .setDescripcion(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getDescripcion())
                                        .setEstado(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().isEstado())
                                        .setCodigo(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getCodigo())
                                )
                        )

                     /*   .setConductorDto( inspeccion.getVehiculo().getConductor() == null? null: new ConductorDto()
                                .setUuid(inspeccion.getVehiculo().getConductor().getUuid())
                                .setNombreCompleto(inspeccion.getVehiculo().getConductor().getNombreCompleto())
                                .setTipoDocumento(inspeccion.getVehiculo().getConductor().getTipoDocumento())
                                .setNumeroDocumento(inspeccion.getVehiculo().getConductor().getNumeroDocumento())
                                .setExpedido(inspeccion.getVehiculo().getConductor().getExpedido())
                                .setEmail(inspeccion.getVehiculo().getConductor().getEmail())
                                .setEstado(inspeccion.getVehiculo().getConductor().isEstado())
                                .setTipoContribuyenteDto(inspeccion.getVehiculo().getConductor().getTipoContribuyente()==null? null: new TipoContribuyenteDto()
                                        .setUuid(inspeccion.getVehiculo().getConductor().getTipoContribuyente().getUuid())
                                        .setDescripcion(inspeccion.getVehiculo().getConductor().getTipoContribuyente().getDescripcion())
                                        .setEstado(inspeccion.getVehiculo().getConductor().getTipoContribuyente().isEstado())
                                        .setCodigo(inspeccion.getVehiculo().getConductor().getTipoContribuyente().getCodigo())
                                )
                        )*/
                )
                .setEventoDto( inspeccion.getEvento() == null ? null: new EventoDto()
                        .setUuid(inspeccion.getVehiculo().getUuid())
                        .setInstitucion(inspeccion.getEvento().getInstitucion())
                        .setFechaInicio(inspeccion.getEvento().getFechaInicio())
                        .setFechaFin(inspeccion.getEvento().getFechaFin())
                        .setHoraInicio(inspeccion.getEvento().getHoraInicio())
                        .setHoraFin(inspeccion.getEvento().getHoraFin())
                        .setLatitud(inspeccion.getEvento().getLatitud())
                        .setLongitud(inspeccion.getEvento().getLongitud())
                        .setDireccion(inspeccion.getEvento().getDireccion())
                        .setDescripcion(inspeccion.getEvento().getDescripcion())
                        .setDistrito(inspeccion.getEvento().getDistrito())
                        .setAltitud(inspeccion.getEvento().getAltitud())
                        .setTitulo(inspeccion.getEvento().getTitulo())
                        .setEstado(inspeccion.getEvento().isEstado())
                )

               /* .setVehiculoConductorInspeccionDtoList(inspeccion.getVehiculoConductorInspeccionList().stream().map(vehiculoConductorInspeccion -> {
                    return VehiculoConductorInspeccionMapper.toVehiculoConductorInspeccionDto(vehiculoConductorInspeccion);
                }).collect(Collectors.toList()))*/

                .setDetalleInspeccionDtoList(inspeccion.getDetalleInspeccionList().stream().map( detalleInspeccion -> {
                        return DetalleInspeccionMapper.toDetalleInspeccionDto(detalleInspeccion);
                }).collect(Collectors.toList()))
                .setRequisitoInspeccionDtoList(inspeccion.getRequisitoInspeccionList().stream().map(requisitoInspeccion -> {
                    return RequisitoInspeccionMapper.toRequisitoInspeccionDto(requisitoInspeccion);
                }).collect(Collectors.toList()))
                ;
    }

    public static Inspeccion toInspeccion(InspeccionDto inspeccionDto){
        return new Inspeccion()
                .setUuid(inspeccionDto.getUuid())
                .setResultado(inspeccionDto.isResultado())
                .setObservacion(inspeccionDto.getObservacion())
                .setFechaInspeccion(inspeccionDto.getFechaInspeccion())
                .setLugarInspeccion(inspeccionDto.getLugarInspeccion())
                .setNombreInspector(inspeccionDto.getNombreInspector())
                .setUuidUsuario(inspeccionDto.getUuidUsuario())
                .setAltitud(inspeccionDto.getAltitud())
                .setEquipo(inspeccionDto.getEquipo())
                .setExamenVisualConforme(inspeccionDto.isExamenVisualConforme())
                .setGasesEscapeConforme(inspeccionDto.isGasesEscapeConforme())
                .setFechaProximaInspeccion(inspeccionDto.getFechaProximaInspeccion())
                .setEstado(inspeccionDto.isEstado())
              /*  .setActividad(inspeccionDto.getActividadDto() == null? null: new Actividad()
                        .setUuid(inspeccionDto.getActividadDto().getUuid())
                        .setActivo(inspeccionDto.getActividadDto().isActivo())
                        .setTipoActividad(inspeccionDto.getActividadDto().getTipoActividad())
                        .setFechaInicio(inspeccionDto.getActividadDto().getFechaInicio())
                        .setFechaFin(inspeccionDto.getActividadDto().getFechaFin())
                        .setEstado(inspeccionDto.getActividadDto().isEstado())
                )

                .setVehiculo(inspeccionDto.getVehiculoDto() == null? null: new Vehiculo()
                        .setUuid(inspeccionDto.getVehiculoDto().getUuid())
                        .setFechaRegistro(inspeccionDto.getVehiculoDto().getFechaRegistro())
                        .setPlaca(inspeccionDto.getVehiculoDto().getPlaca())
                        .setPoliza(inspeccionDto.getVehiculoDto().getPoliza())
                        .setVinNumeroIdentificacion(inspeccionDto.getVehiculoDto().getVinNumeroIdentificacion())
                        .setJuridiccionOrigen(inspeccionDto.getVehiculoDto().getJuridiccionOrigen())
                        .setEsOficial(inspeccionDto.getVehiculoDto().isEsOficial())
                        .setEstado(inspeccionDto.getVehiculoDto().isEstado())
                )*/
                ;
    }
}
