package com.gamq.ambiente.dto.mapper;

import com.gamq.ambiente.dto.*;
import com.gamq.ambiente.model.Actividad;
import com.gamq.ambiente.model.Inspeccion;
import com.gamq.ambiente.model.Propietario;
import com.gamq.ambiente.model.Vehiculo;

import java.util.stream.Collectors;

public class InspeccionMapper {
    public static InspeccionDto toInspeccionDto(Inspeccion inspeccion){
        return new InspeccionDto()
                .setUuid(inspeccion.getUuid())
                .setCodigo(inspeccion.getCodigo())
                .setResultado(inspeccion.isResultado())
                .setObservacion(inspeccion.getObservacion())
                .setFechaInspeccion(inspeccion.getFechaInspeccion())
                .setLugarInspeccion(inspeccion.getLugarInspeccion())
                .setNombreInspector(inspeccion.getNombreInspector())
                .setUuidUsuario(inspeccion.getUuidUsuario())
                .setAltitud(inspeccion.getAltitud())
                .setExamenVisualConforme(inspeccion.isExamenVisualConforme())
                .setGasesEscapeConforme(inspeccion.isGasesEscapeConforme())
                .setFechaProximaInspeccion(inspeccion.getFechaProximaInspeccion())
                .setEstado(inspeccion.isEstado())
                .setEquipoDto(inspeccion.getEquipo()== null? null: new EquipoDto()
                        .setUuid(inspeccion.getEquipo().getUuid())
                        .setNombre(inspeccion.getEquipo().getNombre())
                        .setVersion(inspeccion.getEquipo().getVersion())
                        .setEstado(inspeccion.getEquipo().isEstado())
                )
                .setActividadDto(inspeccion.getActividad() == null? null: new ActividadDto()
                        .setUuid(inspeccion.getActividad().getUuid())
                        .setActivo(inspeccion.getActividad().isActivo())
                        .setTipoActividad(inspeccion.getActividad().getTipoActividad())
                        .setFechaInicio(inspeccion.getActividad().getFechaInicio())
                        .setFechaFin(inspeccion.getActividad().getFechaFin())
                        .setEstado(inspeccion.getActividad().isEstado())
                )
                .setVehiculoDto(inspeccion.getVehiculo() == null? null: new VehiculoDto()
                        .setUuid(inspeccion.getVehiculo().getUuid())
                        .setPlaca(inspeccion.getVehiculo().getPlaca())
                        .setPoliza(inspeccion.getVehiculo().getPoliza())
                        .setVinNumeroIdentificacion(inspeccion.getVehiculo().getVinNumeroIdentificacion())
                        .setEsOficial(inspeccion.getVehiculo().isEsOficial())
                        .setFechaRegistro(inspeccion.getVehiculo().getFechaRegistro())
                        .setJurisdiccionOrigen(inspeccion.getVehiculo().getJurisdiccionOrigen())
                        .setEsMovil(inspeccion.getVehiculo().getEsMovil())
                        .setEsUnidadIndustrial(inspeccion.getVehiculo().isEsUnidadIndustrial())
                        .setPinNumeroIdentificacion(inspeccion.getVehiculo().getPinNumeroIdentificacion())
                        .setNroCopiasPlaca(inspeccion.getVehiculo().getNroCopiasPlaca())
                        .setPlacaAnterior(inspeccion.getVehiculo().getPlacaAnterior())
                        .setChasis(inspeccion.getVehiculo().getChasis())
                        .setEstado(inspeccion.getVehiculo().isEstado())
                        .setDatoTecnicoDto( inspeccion.getVehiculo().getDatoTecnico() == null? null: new DatoTecnicoDto()
                                .setUuid(inspeccion.getVehiculo().getDatoTecnico().getUuid())
                                .setTipoVehiculo(inspeccion.getVehiculo().getDatoTecnico().getTipoVehiculo())
                                .setCapacidadCarga(inspeccion.getVehiculo().getDatoTecnico().getCapacidadCarga())
                                .setCilindrada(inspeccion.getVehiculo().getDatoTecnico().getCilindrada())
                                .setColor(inspeccion.getVehiculo().getDatoTecnico().getColor())
                                .setEmisionStandard(inspeccion.getVehiculo().getDatoTecnico().getEmisionStandard())
                                .setEstado(inspeccion.getVehiculo().getDatoTecnico().isEstado())
                                .setKilometraje(inspeccion.getVehiculo().getDatoTecnico().getKilometraje())
                                .setMarca(inspeccion.getVehiculo().getDatoTecnico().getMarca())
                                .setColor(inspeccion.getVehiculo().getDatoTecnico().getColor())
                                .setModelo(inspeccion.getVehiculo().getDatoTecnico().getModelo())
                                .setNumeroPuertas(inspeccion.getVehiculo().getDatoTecnico().getNumeroPuertas())
                                .setPais(inspeccion.getVehiculo().getDatoTecnico().getPais())
                                .setServicio(inspeccion.getVehiculo().getDatoTecnico().getServicio())
                                .setTamanoMotor(inspeccion.getVehiculo().getDatoTecnico().getTamanoMotor())
                                .setTipoCarroceria(inspeccion.getVehiculo().getDatoTecnico().getTipoCarroceria())
                                .setTraccion(inspeccion.getVehiculo().getDatoTecnico().getTraccion())
                                .setTipoMotor(inspeccion.getVehiculo().getDatoTecnico().getTipoMotor())
                                .setYearFabricacion(inspeccion.getVehiculo().getDatoTecnico().getYearFabricacion())
                                .setClasificacion(inspeccion.getVehiculo().getDatoTecnico().getClasificacion())
                                .setNumeroAsientos(inspeccion.getVehiculo().getDatoTecnico().getNumeroAsientos())
                                .setTiempoMotor(inspeccion.getVehiculo().getDatoTecnico().getTiempoMotor())
                                .setCategoriaVehiculo(inspeccion.getVehiculo().getDatoTecnico().getCategoriaVehiculo())
                                .setEstado(inspeccion.getVehiculo().getDatoTecnico().isEstado())
                                .setTipoClaseVehiculoDto(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo() == null? null: new TipoClaseVehiculoDto()
                                        .setUuid(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getUuid())
                                        .setNombre(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getNombre())
                                        .setDescripcion(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getDescripcion())
                                        .setEstado(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().isEstado())
                                        .setClaseVehiculoDto(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getClaseVehiculo() == null? null: new ClaseVehiculoDto()
                                                .setUuid(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getClaseVehiculo().getUuid())
                                                .setNombre(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getClaseVehiculo().getNombre())
                                                .setDescripcion(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getClaseVehiculo().getDescripcion())
                                                .setEstado(inspeccion.getVehiculo().getDatoTecnico().getTipoClaseVehiculo().getClaseVehiculo().isEstado())
                                        )
                                )
                        )

                        .setPropietarioDto(inspeccion.getVehiculo().getPropietario()== null? null: new PropietarioDto()
                                .setUuid(inspeccion.getVehiculo().getPropietario().getUuid())
                                .setNombre(inspeccion.getVehiculo().getPropietario().getNombre())
                                .setPrimerApellido(inspeccion.getVehiculo().getPropietario().getPrimerApellido())
                                .setSegundoApellido(inspeccion.getVehiculo().getPropietario().getSegundoApellido())
                                .setApellidoEsposo(inspeccion.getVehiculo().getPropietario().getApellidoEsposo())
                                .setEstadoCivil(inspeccion.getVehiculo().getPropietario().getEstadoCivil())
                                .setGenero(inspeccion.getVehiculo().getPropietario().getGenero())
                                .setFechaNacimiento(inspeccion.getVehiculo().getPropietario().getFechaNacimiento())
                                .setNumeroDocumento(inspeccion.getVehiculo().getPropietario().getNumeroDocumento())
                                .setTipoDocumento(inspeccion.getVehiculo().getPropietario().getTipoDocumento())
                                .setExpedido(inspeccion.getVehiculo().getPropietario().getExpedido())
                                .setEmail(inspeccion.getVehiculo().getPropietario().getEmail())
                                .setNroTelefono(inspeccion.getVehiculo().getPropietario().getNroTelefono())
                                .setEstado(inspeccion.getVehiculo().getPropietario().isEstado())
                                .setTipoContribuyenteDto(inspeccion.getVehiculo().getPropietario().getTipoContribuyente()== null? null: new TipoContribuyenteDto()
                                        .setUuid(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getUuid())
                                        .setDescripcion(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getDescripcion())
                                        .setEstado(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().isEstado())
                                        .setCodigo(inspeccion.getVehiculo().getPropietario().getTipoContribuyente().getCodigo())
                                )
                        )
                        .setVehiculoTipoCombustibleDtoList(inspeccion.getVehiculo().getVehiculoTipoCombustibleList().stream().map(vehiculoTipoCombustible -> {
                            return VehiculoTipoCombustibleMapper.toDtoSinVehiculo(vehiculoTipoCombustible);
                        }).collect(Collectors.toList()))
               )
                .setEventoDto( inspeccion.getEvento() == null ? null: new EventoDto()
                        .setUuid(inspeccion.getVehiculo().getUuid())
                        .setInstitucion(inspeccion.getEvento().getInstitucion())
                        .setFechaInicio(inspeccion.getEvento().getFechaInicio())
                        .setFechaFin(inspeccion.getEvento().getFechaFin())
                        .setHoraInicio(inspeccion.getEvento().getHoraInicio())
                        .setHoraFin(inspeccion.getEvento().getHoraFin())
                        .setLatitud(inspeccion.getEvento().getLatitud())
                        .setLongitud(inspeccion.getEvento().getLongitud())
                        .setDireccion(inspeccion.getEvento().getDireccion())
                        .setDescripcion(inspeccion.getEvento().getDescripcion())
                        .setDistrito(inspeccion.getEvento().getDistrito())
                        .setAltitud(inspeccion.getEvento().getAltitud())
                        .setTitulo(inspeccion.getEvento().getTitulo())
                        .setEstado(inspeccion.getEvento().isEstado())
                )

                .setConductorDto( inspeccion.getConductor() == null? null: new ConductorDto()
                            .setUuid(inspeccion.getConductor().getUuid())
                            .setNombre(inspeccion.getConductor().getNombre())
                            .setPrimerApellido(inspeccion.getConductor().getPrimerApellido())
                            .setSegundoApellido(inspeccion.getConductor().getSegundoApellido())
                            .setApellidoEsposo(inspeccion.getConductor().getApellidoEsposo())
                            .setTipoDocumento(inspeccion.getConductor().getTipoDocumento())
                            .setNumeroDocumento(inspeccion.getConductor().getNumeroDocumento())
                            .setExpedido(inspeccion.getConductor().getExpedido())
                            .setNroTelefono(inspeccion.getConductor().getNroTelefono())
                            .setEmail(inspeccion.getConductor().getEmail())
                            .setEstado(inspeccion.getConductor().isEstado())
                            .setTipoContribuyenteDto(inspeccion.getConductor().getTipoContribuyente()==null? null: new TipoContribuyenteDto()
                                    .setUuid(inspeccion.getConductor().getTipoContribuyente().getUuid())
                                    .setDescripcion(inspeccion.getConductor().getTipoContribuyente().getDescripcion())
                                    .setEstado(inspeccion.getConductor().getTipoContribuyente().isEstado())
                                    .setCodigo(inspeccion.getConductor().getTipoContribuyente().getCodigo())
                            )
                )

                .setDetalleInspeccionDtoList(inspeccion.getDetalleInspeccionList().stream().map( detalleInspeccion -> {
                        return DetalleInspeccionMapper.toDetalleInspeccionDtoSinInspeccion(detalleInspeccion);
                }).collect(Collectors.toList()))
                .setRequisitoInspeccionDtoList(inspeccion.getRequisitoInspeccionList().stream().map(requisitoInspeccion -> {
                    return RequisitoInspeccionMapper.toRequisitoInspeccionDto(requisitoInspeccion);
                }).collect(Collectors.toList()))
                ;
    }

    public static Inspeccion toInspeccion(InspeccionDto inspeccionDto){
        return new Inspeccion()
                .setUuid(inspeccionDto.getUuid())
                .setCodigo(inspeccionDto.getCodigo())
                .setResultado(inspeccionDto.isResultado())
                .setObservacion(inspeccionDto.getObservacion())
                .setFechaInspeccion(inspeccionDto.getFechaInspeccion())
                .setLugarInspeccion(inspeccionDto.getLugarInspeccion())
                .setNombreInspector(inspeccionDto.getNombreInspector())
                .setUuidUsuario(inspeccionDto.getUuidUsuario())
                .setAltitud(inspeccionDto.getAltitud())
                .setExamenVisualConforme(inspeccionDto.isExamenVisualConforme())
                .setGasesEscapeConforme(inspeccionDto.isGasesEscapeConforme())
                .setFechaProximaInspeccion(inspeccionDto.getFechaProximaInspeccion())
                .setEstado(inspeccionDto.isEstado())
                ;
    }
}
