package com.gamq.ambiente.dto.mapper;

import com.gamq.ambiente.dto.*;
import com.gamq.ambiente.model.Notificacion;

public class NotificacionMapper {
    public static NotificacionDto toNotificacionDto(Notificacion notificacion){
        return new NotificacionDto()
                .setUuid(notificacion.getUuid())
                .setTypeNotificacion(notificacion.getTypeNotificacion())
                .setFechaNotificacion(notificacion.getFechaNotificacion())
                .setNumeroNotificacion(notificacion.getNumeroNotificacion())
                .setObservacion(notificacion.getObservacion())
                .setFechaAsistencia(notificacion.getFechaAsistencia())
                .setHoraAsistencia(notificacion.getHoraAsistencia())
                .setNombreNotificador(notificacion.getNombreNotificador())
                .setUuidUsuario(notificacion.getUuidUsuario())
                .setActividad(notificacion.getActividad())
                .setDireccion(notificacion.getDireccion())
                .setStatusNotificacion(notificacion.getStatusNotificacion())
                .setNumeroIntento(notificacion.getNumeroIntento())
                .setSancion(notificacion.getSancion())
                .setEsDenuncia(notificacion.isEsDenuncia())
                .setEstado(notificacion.isEstado())
                .setInspeccionDto(notificacion.getInspeccion()== null? null : new InspeccionDto()
                        .setUuid(notificacion.getInspeccion().getUuid())
                        .setResultado(notificacion.getInspeccion().isResultado())
                        .setObservacion(notificacion.getInspeccion().getObservacion())
                        .setFechaInspeccion(notificacion.getInspeccion().getFechaInspeccion())
                        .setLugarInspeccion(notificacion.getInspeccion().getLugarInspeccion())
                        .setNombreInspector(notificacion.getInspeccion().getNombreInspector())
                        .setUuidUsuario(notificacion.getInspeccion().getUuidUsuario())
                        .setAltitud(notificacion.getInspeccion().getAltitud())
                        //.setEquipo(notificacion.getInspeccion().getEquipo())
                        .setExamenVisualConforme(notificacion.getInspeccion().isExamenVisualConforme())
                        .setGasesEscapeConforme(notificacion.getInspeccion().isGasesEscapeConforme())
                        .setFechaProximaInspeccion(notificacion.getInspeccion().getFechaProximaInspeccion())
                        .setEstado(notificacion.getInspeccion().isEstado())
                        //2025
                        .setEquipoDto(notificacion.getInspeccion().getEquipo() == null? null: new EquipoDto()
                                .setUuid(notificacion.getInspeccion().getEquipo().getUuid())
                                .setNombre(notificacion.getInspeccion().getEquipo().getNombre())
                                .setVersion(notificacion.getInspeccion().getEquipo().getVersion())
                                .setEstado(notificacion.getInspeccion().getEquipo().isEstado())
                        )

                        .setActividadDto(notificacion.getInspeccion().getActividad() == null? null: new ActividadDto()
                                .setUuid(notificacion.getInspeccion().getActividad().getUuid())
                                .setActivo(notificacion.getInspeccion().getActividad().isActivo())
                                .setTipoActividad(notificacion.getInspeccion().getActividad().getTipoActividad())
                                .setFechaInicio(notificacion.getInspeccion().getActividad().getFechaInicio())
                                .setFechaFin(notificacion.getInspeccion().getActividad().getFechaFin())
                                .setEstado(notificacion.getInspeccion().getActividad().isEstado())
                        )
                        .setVehiculoDto(notificacion.getInspeccion().getVehiculo() == null? null: new VehiculoDto()
                                .setUuid(notificacion.getInspeccion().getVehiculo().getUuid())
                                .setEsOficial(notificacion.getInspeccion().getVehiculo().isEsOficial())
                                .setFechaRegistro(notificacion.getInspeccion().getVehiculo().getFechaRegistro())
                                .setJurisdiccionOrigen(notificacion.getInspeccion().getVehiculo().getJurisdiccionOrigen())
                                .setPlaca(notificacion.getInspeccion().getVehiculo().getPlaca())
                                .setPoliza(notificacion.getInspeccion().getVehiculo().getPoliza())
                                .setVinNumeroIdentificacion(notificacion.getInspeccion().getVehiculo().getVinNumeroIdentificacion())
                                .setEsUnidadIndustrial(notificacion.getInspeccion().getVehiculo().isEsUnidadIndustrial())
                                .setEsMovil(notificacion.getInspeccion().getVehiculo().getEsMovil())
                                .setPinNumeroIdentificacion(notificacion.getInspeccion().getVehiculo().getPinNumeroIdentificacion())
                                .setNroCopiasPlaca(notificacion.getInspeccion().getVehiculo().getNroCopiasPlaca())
                                .setPlacaAnterior(notificacion.getInspeccion().getVehiculo().getPlacaAnterior())
                                .setChasis(notificacion.getInspeccion().getVehiculo().getChasis())

                                .setPropietarioDto(notificacion.getInspeccion().getVehiculo().getPropietario()== null? null: new PropietarioDto()
                                        .setUuid(notificacion.getInspeccion().getVehiculo().getPropietario().getUuid())
                                        .setNombre(notificacion.getInspeccion().getVehiculo().getPropietario().getNombre())
                                        .setPrimerApellido(notificacion.getInspeccion().getVehiculo().getPropietario().getPrimerApellido())
                                        .setSegundoApellido(notificacion.getInspeccion().getVehiculo().getPropietario().getSegundoApellido())
                                        .setApellidoEsposo(notificacion.getInspeccion().getVehiculo().getPropietario().getApellidoEsposo())
                                        .setNumeroDocumento(notificacion.getInspeccion().getVehiculo().getPropietario().getNumeroDocumento())
                                        .setTipoDocumento(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoDocumento())
                                        .setExpedido(notificacion.getInspeccion().getVehiculo().getPropietario().getExpedido())
                                        .setEmail(notificacion.getInspeccion().getVehiculo().getPropietario().getEmail())
                                        .setNroTelefono(notificacion.getInspeccion().getVehiculo().getPropietario().getNroTelefono())
                                        .setEstado(notificacion.getInspeccion().getVehiculo().getPropietario().isEstado())
                                        .setEstadoCivil(notificacion.getInspeccion().getVehiculo().getPropietario().getEstadoCivil())
                                        .setGenero(notificacion.getInspeccion().getVehiculo().getPropietario().getGenero())
                                        .setFechaNacimiento(notificacion.getInspeccion().getVehiculo().getPropietario().getFechaNacimiento())
                                        .setTipoContribuyenteDto(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoContribuyente()== null? null: new TipoContribuyenteDto()
                                                .setUuid(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoContribuyente().getUuid())
                                                .setDescripcion(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoContribuyente().getDescripcion())
                                                .setEstado(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoContribuyente().isEstado())
                                                .setCodigo(notificacion.getInspeccion().getVehiculo().getPropietario().getTipoContribuyente().getCodigo())
                                        )
                                )
                        )
                        .setConductorDto( notificacion.getInspeccion().getConductor() == null? null: new ConductorDto()
                                .setUuid(notificacion.getInspeccion().getConductor().getUuid())
                                .setNombre(notificacion.getInspeccion().getConductor().getNombre())
                                .setPrimerApellido(notificacion.getInspeccion().getConductor().getPrimerApellido())
                                .setSegundoApellido(notificacion.getInspeccion().getConductor().getSegundoApellido())
                                .setApellidoEsposo(notificacion.getInspeccion().getConductor().getApellidoEsposo())
                                .setTipoDocumento(notificacion.getInspeccion().getConductor().getTipoDocumento())
                                .setNumeroDocumento(notificacion.getInspeccion().getConductor().getNumeroDocumento())
                                .setExpedido(notificacion.getInspeccion().getConductor().getExpedido())
                                .setNroTelefono(notificacion.getInspeccion().getConductor().getNroTelefono())
                                .setEmail(notificacion.getInspeccion().getConductor().getEmail())
                                .setEstado(notificacion.getInspeccion().getConductor().isEstado())
                                .setTipoContribuyenteDto(notificacion.getInspeccion().getConductor().getTipoContribuyente()==null? null: new TipoContribuyenteDto()
                                        .setUuid(notificacion.getInspeccion().getConductor().getTipoContribuyente().getUuid())
                                        .setDescripcion(notificacion.getInspeccion().getConductor().getTipoContribuyente().getDescripcion())
                                        .setEstado(notificacion.getInspeccion().getConductor().getTipoContribuyente().isEstado())
                                        .setCodigo(notificacion.getInspeccion().getConductor().getTipoContribuyente().getCodigo())
                                )
                        )
                )
                ;
    }

    public static Notificacion toNotificacion( NotificacionDto notificacionDto){
        return new Notificacion()
                .setUuid(notificacionDto.getUuid())
                .setTypeNotificacion(notificacionDto.getTypeNotificacion())
                .setFechaNotificacion(notificacionDto.getFechaNotificacion())
                .setNumeroNotificacion(notificacionDto.getNumeroNotificacion())
                .setObservacion(notificacionDto.getObservacion())
                .setFechaAsistencia(notificacionDto.getFechaAsistencia())
                .setHoraAsistencia(notificacionDto.getHoraAsistencia())
                .setNombreNotificador(notificacionDto.getNombreNotificador())
                .setUuidUsuario(notificacionDto.getUuidUsuario())
                .setActividad(notificacionDto.getActividad())
                .setDireccion(notificacionDto.getDireccion())
                .setStatusNotificacion(notificacionDto.getStatusNotificacion())
                .setNumeroIntento(notificacionDto.getNumeroIntento())
                .setSancion(notificacionDto.getSancion())
                .setEsDenuncia(notificacionDto.isEsDenuncia())
                .setEstado(notificacionDto.isEstado())
                ;
    }
}
