package com.gamq.ambiente.dto.mapper;

import com.gamq.ambiente.dto.*;
import com.gamq.ambiente.model.*;

public class VehiculoConductorInspeccionMapper {
    public static VehiculoConductorInspeccionDto toVehiculoConductorInspeccionDto(VehiculoConductorInspeccion vehiculoConductorInspeccion){
        return new VehiculoConductorInspeccionDto()
                .setUuid(vehiculoConductorInspeccion.getUuid())
                .setVehiculoDto(vehiculoConductorInspeccion.getVehiculo() == null ? null: new VehiculoDto()
                        .setUuid(vehiculoConductorInspeccion.getVehiculo().getUuid())
                        .setEsOficial(vehiculoConductorInspeccion.getVehiculo().isEsOficial())
                        .setFechaRegistro(vehiculoConductorInspeccion.getVehiculo().getFechaRegistro())
                        .setJurisdiccionOrigen(vehiculoConductorInspeccion.getVehiculo().getJurisdiccionOrigen())
                        .setPlaca(vehiculoConductorInspeccion.getVehiculo().getPlaca())
                        .setPoliza(vehiculoConductorInspeccion.getVehiculo().getPoliza())
                        .setVinNumeroIdentificacion(vehiculoConductorInspeccion.getVehiculo().getVinNumeroIdentificacion())
                        .setEstado(vehiculoConductorInspeccion.getVehiculo().isEstado())
                        .setEsUnidadIndustrial(vehiculoConductorInspeccion.getVehiculo().isEsUnidadIndustrial())
                        .setEsMovil(vehiculoConductorInspeccion.getVehiculo().getEsMovil())
                        .setPinNumeroIdentificacion(vehiculoConductorInspeccion.getVehiculo().getPinNumeroIdentificacion())
                        .setNroCopiasPlaca(vehiculoConductorInspeccion.getVehiculo().getNroCopiasPlaca())
                        .setPlacaAnterior(vehiculoConductorInspeccion.getVehiculo().getPlacaAnterior())
                        .setChasis(vehiculoConductorInspeccion.getVehiculo().getChasis())
                )
                .setConductorDto(vehiculoConductorInspeccion.getConductor()==null? null: new ConductorDto()
                        .setUuid(vehiculoConductorInspeccion.getConductor().getUuid())
                        .setExpedido(vehiculoConductorInspeccion.getConductor().getExpedido())
                        .setNombreCompleto(vehiculoConductorInspeccion.getConductor().getNombreCompleto())
                        .setNumeroDocumento(vehiculoConductorInspeccion.getConductor().getNumeroDocumento())
                        .setTipoDocumento(vehiculoConductorInspeccion.getConductor().getTipoDocumento())
                        .setEmail(vehiculoConductorInspeccion.getConductor().getEmail())
                        .setEstado(vehiculoConductorInspeccion.getConductor().isEstado())
                        .setTipoContribuyenteDto(vehiculoConductorInspeccion.getConductor().getTipoContribuyente() == null? null: new TipoContribuyenteDto()
                                .setUuid(vehiculoConductorInspeccion.getConductor().getTipoContribuyente().getUuid())
                                .setDescripcion(vehiculoConductorInspeccion.getConductor().getTipoContribuyente().getDescripcion())
                                .setCodigo(vehiculoConductorInspeccion.getConductor().getTipoContribuyente().getCodigo())
                                .setEstado(vehiculoConductorInspeccion.getConductor().getTipoContribuyente().isEstado())
                        )
                )
                .setInspeccionDto(vehiculoConductorInspeccion.getInspeccion()== null? null: new InspeccionDto()
                        .setUuid(vehiculoConductorInspeccion.getInspeccion().getUuid())
                        .setResultado(vehiculoConductorInspeccion.getInspeccion().isResultado())
                        .setObservacion(vehiculoConductorInspeccion.getInspeccion().getObservacion())
                        .setFechaInspeccion(vehiculoConductorInspeccion.getInspeccion().getFechaInspeccion())
                        .setLugarInspeccion(vehiculoConductorInspeccion.getInspeccion().getLugarInspeccion())
                        .setNombreInspector(vehiculoConductorInspeccion.getInspeccion().getNombreInspector())
                        .setUuidUsuario(vehiculoConductorInspeccion.getInspeccion().getUuidUsuario())
                        .setAltitud(vehiculoConductorInspeccion.getInspeccion().getAltitud())
                        .setEquipo(vehiculoConductorInspeccion.getInspeccion().getEquipo())
                        .setExamenVisualConforme(vehiculoConductorInspeccion.getInspeccion().isExamenVisualConforme())
                        .setGasesEscapeConforme(vehiculoConductorInspeccion.getInspeccion().isGasesEscapeConforme())
                        .setFechaProximaInspeccion(vehiculoConductorInspeccion.getInspeccion().getFechaProximaInspeccion())
                        .setEstado(vehiculoConductorInspeccion.getInspeccion().isEstado())
                        .setActividadDto(vehiculoConductorInspeccion.getInspeccion().getActividad() == null? null: new ActividadDto()
                                .setUuid(vehiculoConductorInspeccion.getInspeccion().getActividad().getUuid())
                                .setActivo(vehiculoConductorInspeccion.getInspeccion().getActividad().isActivo())
                                .setTipoActividad(vehiculoConductorInspeccion.getInspeccion().getActividad().getTipoActividad())
                                .setFechaInicio(vehiculoConductorInspeccion.getInspeccion().getActividad().getFechaInicio())
                                .setFechaFin(vehiculoConductorInspeccion.getInspeccion().getActividad().getFechaFin())
                                .setEstado(vehiculoConductorInspeccion.getInspeccion().getActividad().isEstado())
                        )
                )
                .setEstado(vehiculoConductorInspeccion.isEstado())
                ;
    }
    public static VehiculoConductorInspeccion toVehiculoConductorInspeccion(VehiculoConductorInspeccionDto vehiculoConductorInspeccionDto){
        return new VehiculoConductorInspeccion()
                .setUuid(vehiculoConductorInspeccionDto.getUuid())
                .setVehiculo(vehiculoConductorInspeccionDto.getVehiculoDto() == null ? null: new Vehiculo()
                        .setUuid(vehiculoConductorInspeccionDto.getVehiculoDto().getUuid())
                        .setEsOficial(vehiculoConductorInspeccionDto.getVehiculoDto().isEsOficial())
                        .setFechaRegistro(vehiculoConductorInspeccionDto.getVehiculoDto().getFechaRegistro())
                        .setJurisdiccionOrigen(vehiculoConductorInspeccionDto.getVehiculoDto().getJurisdiccionOrigen())
                        .setPlaca(vehiculoConductorInspeccionDto.getVehiculoDto().getPlaca())
                        .setPoliza(vehiculoConductorInspeccionDto.getVehiculoDto().getPoliza())
                        .setVinNumeroIdentificacion(vehiculoConductorInspeccionDto.getVehiculoDto().getVinNumeroIdentificacion())
                        .setEstado(vehiculoConductorInspeccionDto.getVehiculoDto().isEstado())
                        .setEsUnidadIndustrial(vehiculoConductorInspeccionDto.getVehiculoDto().isEsUnidadIndustrial())
                        .setEsMovil(vehiculoConductorInspeccionDto.getVehiculoDto().getEsMovil())
                        .setPinNumeroIdentificacion(vehiculoConductorInspeccionDto.getVehiculoDto().getPinNumeroIdentificacion())
                        .setNroCopiasPlaca(vehiculoConductorInspeccionDto.getVehiculoDto().getNroCopiasPlaca())
                        .setPlacaAnterior(vehiculoConductorInspeccionDto.getVehiculoDto().getPlacaAnterior())
                        .setChasis(vehiculoConductorInspeccionDto.getVehiculoDto().getChasis())
                )
                .setConductor(vehiculoConductorInspeccionDto.getConductorDto()==null? null: new Conductor()
                        .setUuid(vehiculoConductorInspeccionDto.getConductorDto().getUuid())
                        .setExpedido(vehiculoConductorInspeccionDto.getConductorDto().getExpedido())
                        .setNombreCompleto(vehiculoConductorInspeccionDto.getConductorDto().getNombreCompleto())
                        .setNumeroDocumento(vehiculoConductorInspeccionDto.getConductorDto().getNumeroDocumento())
                        .setTipoDocumento(vehiculoConductorInspeccionDto.getConductorDto().getTipoDocumento())
                        .setEmail(vehiculoConductorInspeccionDto.getConductorDto().getEmail())
                        .setEstado(vehiculoConductorInspeccionDto.getConductorDto().isEstado())
                        .setTipoContribuyente(vehiculoConductorInspeccionDto.getConductorDto().getTipoContribuyenteDto() == null? null: new TipoContribuyente()
                                .setUuid(vehiculoConductorInspeccionDto.getConductorDto().getTipoContribuyenteDto().getUuid())
                                .setDescripcion(vehiculoConductorInspeccionDto.getConductorDto().getTipoContribuyenteDto().getDescripcion())
                                .setCodigo(vehiculoConductorInspeccionDto.getConductorDto().getTipoContribuyenteDto().getCodigo())
                                .setEstado(vehiculoConductorInspeccionDto.getConductorDto().getTipoContribuyenteDto().isEstado())
                        )
                )
                .setInspeccion(vehiculoConductorInspeccionDto.getInspeccionDto()== null? null: new Inspeccion()
                        .setUuid(vehiculoConductorInspeccionDto.getInspeccionDto().getUuid())
                        .setResultado(vehiculoConductorInspeccionDto.getInspeccionDto().isResultado())
                        .setObservacion(vehiculoConductorInspeccionDto.getInspeccionDto().getObservacion())
                        .setFechaInspeccion(vehiculoConductorInspeccionDto.getInspeccionDto().getFechaInspeccion())
                        .setLugarInspeccion(vehiculoConductorInspeccionDto.getInspeccionDto().getLugarInspeccion())
                        .setNombreInspector(vehiculoConductorInspeccionDto.getInspeccionDto().getNombreInspector())
                        .setUuidUsuario(vehiculoConductorInspeccionDto.getInspeccionDto().getUuidUsuario())
                        .setAltitud(vehiculoConductorInspeccionDto.getInspeccionDto().getAltitud())
                        .setEquipo(vehiculoConductorInspeccionDto.getInspeccionDto().getEquipo())
                        .setExamenVisualConforme(vehiculoConductorInspeccionDto.getInspeccionDto().isExamenVisualConforme())
                        .setGasesEscapeConforme(vehiculoConductorInspeccionDto.getInspeccionDto().isGasesEscapeConforme())
                        .setFechaProximaInspeccion(vehiculoConductorInspeccionDto.getInspeccionDto().getFechaProximaInspeccion())
                        .setEstado(vehiculoConductorInspeccionDto.getInspeccionDto().isEstado())
                        .setActividad(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto() == null? null: new Actividad()
                                .setUuid(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().getUuid())
                                .setActivo(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().isActivo())
                                .setTipoActividad(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().getTipoActividad())
                                .setFechaInicio(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().getFechaInicio())
                                .setFechaFin(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().getFechaFin())
                                .setEstado(vehiculoConductorInspeccionDto.getInspeccionDto().getActividadDto().isEstado())
                        )
                )
                .setEstado(vehiculoConductorInspeccionDto.isEstado());
    }
}
